// QP 0.2.3
// This script takes the values generated by the Add smoothed features plugin to create a cell density map that can be viewed in Measure->Measurement Maps
// For example, Tumor cells would show up in the Measurement List as "Nearby cells - Tumor"
// Local density will be based on the radius used during Add smoothed features.

//////////CHANGE THIS //////
String smoothedRadius = 15
////////////////////////////

//Alternatively, remove this line and use the Analyze->Calculate Features-> Add smoothed features with Smooth within classes checked.
selectAnnotations()
runPlugin('qupath.lib.plugins.objects.SmoothFeaturesPlugin', '{"fwhmMicrons": '+smoothedRadius+',  "smoothWithinClasses": true}');

classList = getCurrentHierarchy().getDetectionObjects().collect{it.getPathClass()} as Set

//Find the smoothed count


classList.each{c->
    cellList = getCellObjects().findAll{it.getPathClass() == c}
    cellList.each{
        it.getMeasurementList().putMeasurement("Nearby cells - "+ c.toString(), measurement(it,"Smoothed: "+smoothedRadius+" µm: Nearby detection counts"))
    }
    //getCellObjects().findAll{it.getPathClass() != c}.each{it.getMeasurementList().putMeasurement("Nearby cells - "+ c.toString(), 0)}
}
    
print "Done"